openapi: 3.0.0
info:
  title: Library API
  version: 1.0
paths:
  /books:
    post:
      responses:
        "200":
          description: Book added
  /books/{id}:
    put:
      parameters:
        - name: id
          in: path
          required: true
      responses:
        "200":
          description: Book updated
    get:
      parameters:
        - name: id
          in: path
          required: true
      responses:
        "200":
          description: Book fetched
